import { defineConfig } from 'vite'
import fs from 'fs'
import path from 'path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'


const PLACEHOLDER = path.resolve(
  __dirname,
  'src/assets/_missing-asset-placeholder.svg',
)

// A handful of assets referenced by the case-study pages were never included in
// the Figma Make export. Rather than failing the production build, resolve them
// to a visible placeholder and warn — dropping the real file into src/assets
// under its original hashed filename makes it resolve normally again.
function figmaAssetResolver() {
  const warned = new Set<string>()

  return {
    name: 'figma-asset-resolver',
    resolveId(id: string) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        const resolved = path.resolve(__dirname, 'src/assets', filename)

        // Prefer the WebP generated by `npm run optimize:images` when present —
        // same image, a fraction of the bytes, no page edits required.
        const webp = resolved.replace(/\.png$/i, '.webp')
        if (webp !== resolved && fs.existsSync(webp)) {
          return webp
        }

        if (!fs.existsSync(resolved)) {
          if (!warned.has(filename)) {
            warned.add(filename)
            console.warn(
              `\n[figma-asset] MISSING: src/assets/${filename}\n` +
                `              serving placeholder instead — export it from Figma to fix.\n`,
            )
          }
          return PLACEHOLDER
        }

        return resolved
      }
    },
  }
}

export default defineConfig({
  plugins: [
    figmaAssetResolver(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
